# Diff Torch functions

### Intro into torch functions

An short introduction about PyTorch and about the chosen functions. 
- torch.tensor
- torch.diagonal
- Torch.reshape
- Torch.multiply
- torch.unfold

In [1]:
# Import torch and other required modules
import torch

# Torch.tensor

which creates the tensor

In [10]:
# Example 1 - working (change this)
torch.tensor(1.)

tensor(1.)

Explanation about example

In [11]:
# Example 2 - working
torch.tensor([1.,2.,4.])

tensor([1., 2., 4.])

Explanation about example

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
torch.tensor([[1.,2,3],[4,5,6],[6,7]])

ValueError: expected sequence of length 3 at dim 1 (got 2)

Explanation about example

Closing comments about when to use this function

## Torch Diagonal

Generates ones

In [18]:
# Example 1 - working
d=torch.zeros(5,3)
d.fill_diagonal_(5)

tensor([[5., 0., 0.],
        [0., 5., 0.],
        [0., 0., 5.],
        [0., 0., 0.],
        [0., 0., 0.]])

Explanation about example

In [19]:
# Example 2 - working
d=torch.ones(5,3)
d.fill_diagonal_(5)

tensor([[5., 1., 1.],
        [1., 5., 1.],
        [1., 1., 5.],
        [1., 1., 1.],
        [1., 1., 1.]])

Explanation about example

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
d=torch.ones(2,3,1)
d.fill_diagonal_(5)

RuntimeError: all dimensions of input must be of equal length

Explanation about example

Closing comments about when to use this function

## Torch.reshape

Add some explanations

In [34]:
# Example 1 - working
x=torch.rand(3,4)
print(x)
x.reshape(1,12)
#torch.rand()

tensor([[0.0978, 0.2699, 0.5179, 0.1201],
        [0.2568, 0.1225, 0.6472, 0.3555],
        [0.8989, 0.7158, 0.1014, 0.0667]])


tensor([[0.0978, 0.2699, 0.5179, 0.1201, 0.2568, 0.1225, 0.6472, 0.3555, 0.8989,
         0.7158, 0.1014, 0.0667]])

Explanation about example

In [37]:
# Example 2 - working
x=torch.rand(5,6)
print(x)
x.reshape(6,5)

tensor([[0.8895, 0.6361, 0.4477, 0.5347, 0.1423, 0.7688],
        [0.9413, 0.7520, 0.2398, 0.7342, 0.1670, 0.8882],
        [0.0768, 0.1640, 0.5040, 0.6656, 0.6336, 0.7304],
        [0.1522, 0.4939, 0.8395, 0.7388, 0.3662, 0.2817],
        [0.7315, 0.3878, 0.9273, 0.0397, 0.2097, 0.6143]])


tensor([[0.8895, 0.6361, 0.4477, 0.5347, 0.1423],
        [0.7688, 0.9413, 0.7520, 0.2398, 0.7342],
        [0.1670, 0.8882, 0.0768, 0.1640, 0.5040],
        [0.6656, 0.6336, 0.7304, 0.1522, 0.4939],
        [0.8395, 0.7388, 0.3662, 0.2817, 0.7315],
        [0.3878, 0.9273, 0.0397, 0.2097, 0.6143]])

Explanation about example

In [39]:
# Example 3 - breaking (to illustrate when it breaks)
x=torch.rand(2,3)
print(x)
x.reshape(3,3)

tensor([[0.3648, 0.7032, 0.1065],
        [0.4339, 0.3686, 0.6971]])


RuntimeError: shape '[3, 3]' is invalid for input of size 6

Explanation about example

Closing comments about when to use this function

## Torch.multiply

Add some explanations

In [45]:
# Example 1 - working
x=torch.tensor([2])
y=torch.tensor([3])
z=x@y
z

tensor(6)

Explanation about example

In [46]:
# Example 2 - working
x=torch.tensor([[2,3],[4,5]])
y=torch.tensor([[3,2],[5,4]])
z=x@y
z

tensor([[21, 16],
        [37, 28]])

Explanation about example

In [49]:
# Example 3 - breaking (to illustrate when it breaks)
x=torch.tensor([[2,3],[4,5]])
y=torch.tensor([[3,2],[5,4],[7,8]])
z=x@y
z

RuntimeError: size mismatch, m1: [2 x 2], m2: [3 x 2] at /opt/conda/conda-bld/pytorch_1587428266983/work/aten/src/TH/generic/THTensorMath.cpp:41

Explanation about example

Closing comments about when to use this function

## Torch.unfold

Add some explanations

In [57]:
# Example 1 - working
x = torch.arange(1., 10)
x
x.unfold(0,2,1)

tensor([[1., 2.],
        [2., 3.],
        [3., 4.],
        [4., 5.],
        [5., 6.],
        [6., 7.],
        [7., 8.],
        [8., 9.]])

Explanation about example

In [61]:
# Example 2 - working
x = torch.arange(1., 10)
x
x.unfold(-1,1,3)

tensor([[1.],
        [4.],
        [7.]])

Explanation about example

In [62]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.arange(1., 10)
x
x.unfold(0,2,0)

RuntimeError: step is 0 but must be > 0

Explanation about example

Closing comments about when to use this function

## Conclusion

In this notebook 5 functions of the pytorch functions were executed from when it exectues and breaks

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [63]:
!pip install jovian --upgrade --quiet

In [64]:
import jovian

In [65]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/adityanagraj/diff-tensor-functions


'https://jovian.ml/adityanagraj/diff-tensor-functions'